### PR TITLE
Move caret to text of end when paste in front of open quote

### LINKED ISSUE #2675: Caret placement issue on paste before an open quote
When the caret in front of a quote, pasting successfully pastes but puts the carat in the wrong position.

One could also argue that it shouldn't paste.

### PR DESCRIPTION
**Pull request by br1anchen**
## What is the problem/goal being addressed?
Put caret at the end of text if paste in front of open quote, to fix #2675 

## What are the changes here? How do they solve the problem and what other product impacts do they cause?
*Please include before/after screenshots/gifs if appropriate*
paste-before-open-quote-2020-07

### CODE REVIEW

File: client/src/fluid/Fluid.ml [hunk 1]
```diff
@@ -5417,13 +5417,17 @@ let pasteOverSelection (data : clipboardContents) (astInfo : ASTInfo.t) :
         ->
           (* Paste into a string, to take care of newlines.
            * Note: pasting before an open quote
-           * places the caret one unit left of the text end *)
```
Comment (br1anchen) [inline client/src/fluid/Fluid.ml:5420]: It seems like putting `caret one unit left of the text end` is intended. But not sure what it is for?

Comment (pbiggar) [reply client/src/fluid/Fluid.ml:5420]: That seems like it's commenting on the bug you're fixing (as opposed to documenting expected behaviour), so you can just remove the comment.

File: client/src/fluid/Fluid.ml [hunk 2]
```diff
@@ -5417,13 +5417,17 @@ let pasteOverSelection (data : clipboardContents) (astInfo : ASTInfo.t) :
...
+           * places the caret at the text end *)
           let replacement =
             E.EString (id, String.insertAt ~insert:text ~index:(offset - 1) str)
           in
           let newAST = FluidAST.replace ~replacement id ast in
           let caretTarget =
-            CT.forARStringOpenQuote id (offset + String.length text)
+            match offset with
```
Comment (pbiggar) [inline client/src/fluid/Fluid.ml:5426]: I think an if statement here would be better, since we don't expect to have other offsets.

Comment (br1anchen) [reply client/src/fluid/Fluid.ml]: Right, makes sense.

**Comment by br1anchen** [comment]
@pbiggar Changed as you suggest and add test for this paste string case.

**Comment by pbiggar** [comment]
Wonderful, thank you!
