### PR TITLE
Include metadata in F# Wasm exceptions

### LINKED ISSUE #3577: Report exception metadata in blazor
In #3576, the metadata field "expr" from the exception was not reported to rollbar or to the console. We should report it as that's where we put the important context-sensitive info to debug the exception.

### PR DESCRIPTION
**Pull request by StachuDotNet**
Aimed to resolve #3577.

Tested locally by updating `src/LibExecution/OCamlTypes.fs` locally, commenting out the handling of `EIntegers` from `rt2ocamlExpr`, and running an analysis on something that returned an Int.
image

If I try to change the shape of the Error returned (e.g. by returning an anonymous record of `{ message: string, metadata: ...}` , I get issues in decoding the error on the client. So, I shoe-horned both into the string - happy to take recommendations there.

### CODE REVIEW

File: fsharp-backend/src/Wasm/Wasm.fs [hunk 1]
```diff
@@ -310,10 +310,13 @@ type EvalWorker =
           )
         with
         | e ->
```
Comment (StachuDotNet) [inline fsharp-backend/src/Wasm/Wasm.fs:312]: The 'top' case here handles parsing, and the below one handles exceptions running analysis.

**Comment by pbiggar** [comment]
> If I try to change the shape of the Error returned (e.g. by returning an anonymous record of { message: string, metadata: ...} , I get issues in decoding the error on the client. So, I shoe-horned both into the string - happy to take recommendations there.

We can do better on the client another day!
