### PR TITLE
Libstaticassets cleanup

### LINKED ISSUE #2408: Docstring in StaticAssets::serve is wrong

### PR DESCRIPTION
**Pull request by StachuDotNet**
Resolves #2408 and a few CLEANUP items

### CODE REVIEW

File: fsharp-backend/src/BackendOnlyStdLib/LibStaticAssets.fs [hunk 1]
```diff
@@ -151,8 +150,6 @@ let fns : List<BuiltInFn> =
         (function
         | state, [] ->
           uply {
-            // CLEANUP calling this with no deploy hash generates an error
-            // (should be Option<TStr>)
```
Comment (StachuDotNet) [inline fsharp-backend/src/BackendOnlyStdLib/LibStaticAssets.fs:155]: Ah - should I change this to Option, actually?

File: fsharp-backend/src/BackendOnlyStdLib/LibStaticAssets.fs [hunk 2]
```diff
@@ -138,8 +138,7 @@ let fns : List<BuiltInFn> =
           SA.url state.program.canvasName deployHash SA.Short |> DStr |> Ply
         | _ -> incorrectArgs ())
       sqlSpec = NotQueryable
-      // CLEANUP may be marked as ImpurePreviewable
-      previewable = Impure
+      previewable = ImpurePreviewable
```
Comment (pbiggar) [inline fsharp-backend/src/BackendOnlyStdLib/LibStaticAssets.fs:141]: Am I wrong in thinking this is pure?

File: fsharp-backend/src/BackendOnlyStdLib/LibStaticAssets.fs (hunk 1 above)
Comment (pbiggar) [reply fsharp-backend/src/BackendOnlyStdLib/LibStaticAssets.fs:155]: Yes! (deprecate + new, obvi)

Comment (pbiggar) [reply fsharp-backend/src/BackendOnlyStdLib/LibStaticAssets.fs:155]: Yes,  I think an option rather than a result

File: fsharp-backend/src/BackendOnlyStdLib/LibStaticAssets.fs [hunk 3]
```diff
@@ -175,8 +193,7 @@ let fns : List<BuiltInFn> =
           SA.urlFor state.program.canvasName deployHash SA.Short file |> DStr |> Ply
         | _ -> incorrectArgs ())
       sqlSpec = NotQueryable
-      // CLEANUP may be marked as ImpurePreviewable
-      previewable = Impure
+      previewable = ImpurePreviewable
```
Comment (pbiggar) [inline fsharp-backend/src/BackendOnlyStdLib/LibStaticAssets.fs:196]: Seems Pure to me

**Comment by pbiggar** [comment]
> We could avoid this questino for now and just live with the Pure function requiring a play button. Seems like a waste, though.

You're right that there's no config in LibExecution. So the option would be to pass it in, possibly as part of ExecutionState. But I think we're better off reverting the move to LibExecution for now. Done is better than perfect.

**Comment by StachuDotNet** [comment]
Actually - are the functions really pure if they will changed based on the salt? I think no, in which case ImpurePreviewable is actually right.

File: fsharp-backend/src/BackendOnlyStdLib/LibStaticAssets.fs [hunk 4]
```diff
@@ -162,6 +161,27 @@ let fns : List<BuiltInFn> =
         | _ -> incorrectArgs ())
       sqlSpec = NotQueryable
       previewable = Impure
+      deprecated = ReplacedBy(fn "StaticAssets" "baseUrlForLatest" 1) }
+
+
+    { name = fn "StaticAssets" "baseUrlForLatest" 1
+      parameters = []
+      returnType = TOption varA
```
Comment (pbiggar) [inline fsharp-backend/src/BackendOnlyStdLib/LibStaticAssets.fs:169]:
```suggestion
      returnType = TOption TStr
```

File: fsharp-backend/src/BackendOnlyStdLib/LibStaticAssets.fs [hunk 5]
```diff
@@ -162,6 +161,27 @@ let fns : List<BuiltInFn> =
...
+      description = "Return the baseUrl for the latest deploy"
```
Comment (pbiggar) [inline fsharp-backend/src/BackendOnlyStdLib/LibStaticAssets.fs:170]: This should mention an Option

File: fsharp-backend/tests/testfiles/staticassets.tests [hunk 6]
```diff
@@ -60,12 +60,20 @@ StaticAssets.baseUrlFor_v0 "abcdefghi" = "https://test-baseurlfor-0.darksa.com/g
...
+[tests.baseUrlForLatest_v0 with no hash]
 StaticAssets.baseUrlForLatest_v0 = Test.typeError_v0 "No deploy hash found"
 
+[test.baseUrlForLatest_v1] with ExactCanvasName test-baseurlforlatest-1, StaticAssetsDeployHash abcdef1235
+StaticAssets.baseUrlForLatest_v1 = Some "https://test-baseurlforlatest-1.darksa.com/preb3tbz8blanninut_61rbtx-s/abcdef1235"
+
+[tests.baseUrlForLatest_v1with no hash]
+StaticAssets.baseUrlForLatest_v1 = None
+
+// urlFor
```
Comment (pbiggar) [inline fsharp-backend/tests/testfiles/staticassets.tests:75]: Duplicate comment

**Review by pbiggar — APPROVED** [review]
Looks good with these changes.
